### ISSUE TITLE
Schematic Error at P1

### ISSUE THREAD

**Issue by tbitson** [JuiceBoxZero/LowBatteryShutdown#4]
The schematic shows an inconsistency at P1 USB Power:
P1-1 is labeled VBUS yet is connected to GND
P1-5 is labeled GND but is connected to VBUS
P1 labeling is correct, the connection just seem to be transposed.

**Comment by JuiceBoxZero** [comment]
Thanks for catching this! the SVG export seems to have caused some issues. The schematic is now in PDF format and should be correct. 
Thanks!
